baseURL = "https://ribhu.in/"
title = "Ribhu Ratnam"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Ribhu Ratnam's website"
  copyright = "Ribhu Ratnam"
  dark = "auto"
  highlight = true
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "papershelf"
    name = "papershelf"
    title = "papershelf"
    url = "/papers/"
    weight = 30

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
